### ISSUE TITLE
Failed to submit to detection leaderboard

### ISSUE THREAD

**Issue by foolhard** [argoverse/av2-api#203]
Hello, 

I try to submit to detection leaderboard but got the error as below:

```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 487, in run_submission
    submission_output = EVALUATION_SCRIPTS[challenge_id].evaluate(
  File "/tmp/tmprewoo26e/compute/challenge_data/challenge_1710/main.py", line 50, in evaluate
    _, _, metrics = detection_utils.evaluate(dts, gts, cfg)
  File "/usr/local/lib/python3.8/site-packages/av2/evaluation/detection/eval.py", line 112, in evaluate
    raise ValueError(
ValueError: ROI pruning has been enabled, but the dataset directory has not be specified. Please set `dataset_directory` to the split root, e.g. av2/sensor/val.
```

Please help this issue.

**Comment by foolhard** [comment]
It worked and got results. Thanks for quick support.
